config/routes.rb
Rails.application.routes.draw do

  root 							          'static_pages#home'
  get   	 'contact' 		  =>  'static_pages#contact'
  get		   'addequipment'	=>	'equipment#new'
  get      'makerequest'  =>  'requests#new'
  get		   'signup' 		  =>	'admins#new'
  get		   'login'			  =>	'sessions#new'
  post		 'login'			  =>	'sessions#create'
  delete	 'logout'		    =>	'sessions#destroy'
  resources :admins do
    member do
      get :signed_out, :signed_out_by
      get :signed_in, :signed_in_by
    end
  end
  resources :equipment
  resources :requests,  only: [:new, :create, :index, :destroy]
  resources :sign_outs,   only: [:create, :destroy]
  resources :sign_ins,   only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

	def gravatar_for(name, email)
		gravatar_id = Digest::MD5::hexdigest(email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: name, class: "gravatar")
	end
end

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1><%= gravatar_for("Daniel Swain Jr", "danieswain@gmail.com")%> Daniel Swain Jr</h1>
<p class="center">Contact Daniel Swain Jr about this Equipment Checkout App <a href="http://github.com/wisard1862">here</a>.</p>

app/views/static_pages/home.html.erb
<div class="container jumbotron">
	<h1>Welcome to<br/> Equipment Checkout</h1>
	<p class='center'><%= link_to 'Click here to make a request!',makerequest_path %></p>
</div>