config/routes.rb
Rails.application.routes.draw do

  root 							          'static_pages#home'
  get   	 'contact' 		  =>  'static_pages#contact'
  get		   'addequipment'	=>	'equipment#new'
  get      'makerequest'  =>  'requests#new'
  get		   'signup' 		  =>	'admins#new'
  get		   'login'			  =>	'sessions#new'
  post		 'login'			  =>	'sessions#create'
  delete	 'logout'		    =>	'sessions#destroy'
  resources :admins do
    member do
      get :signed_out, :signed_out_by
      get :signed_in, :signed_in_by
    end
  end
  resources :equipment
  resources :requests,  only: [:new, :create, :index, :destroy]
  resources :sign_outs,   only: [:create, :destroy]
  resources :sign_ins,   only: [:create, :destroy]
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
	has_many :requests, dependent: :destroy
	before_save { self.tag.downcase! }
	default_scope -> { order(tag: :asc) }
	validates :name, presence: true, 
					length: { maximum: 50 }

	VALID_TAG_REGEX = /\A[a-zA-Z]+\d+\z/i
	validates :tag, presence: true,
					length: { maximum: 8 },
					format: { with: VALID_TAG_REGEX },
					uniqueness: { case_sensitive: false }

	validates :status, presence: true
	validates_numericality_of :status, greater_than: 0, less_than: 3

	def name_with_tag
    	"#{tag}:#{name}"
	end

	def set_to_out
		status = 1
	end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :logged_in_admin, only: 
  [:new, :create, :show, :index, :edit, :update, :destroy]

  def new
    @equipment = Equipment.new
  end

  def create
    @equipment = Equipment.new(equipment_params)
    if @equipment.save
      flash[:success] = "Equipment Successfully Added!"
      redirect_to @equipment
    else
      render 'new'
    end
  end

  def show
    @equipment = Equipment.find(params[:id])
  end

  def index
    @equipment = Equipment.paginate(page: params[:page])
  end

  def edit
    @equipment = Equipment.find(params[:id])
  end

  def update
    @equipment = Equipment.find(params[:id])
    if @equipment.update_attributes(equipment_params)
      flash[:success] = "Equipment updated"
      redirect_to @equipment
    else
      render 'edit'
    end
  end

  def destroy
    @name = Equipment.find(params[:id]).name
    Equipment.find(params[:id]).destroy
    flash[:success] = "#{@name} deleted."
    redirect_to equipment_index_path
  end

  private 

    def equipment_params
      params.fetch(:equipment, {}).permit(:tag, :name, :status)
    end

    def logged_in_admin
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
	# Takes the status of the equipment and tells whether it's in or out.
	def give_status(status)
		if status == 2
			"IN"
		else
			"OUT"
		end
	end

end

app/views/equipment/_equipment.html.erb
<tr>
	<td>
		<%= equipment.tag %>
	</td>
	<td>
		<%= equipment.name %>
	</td>
	<td>
		<%= give_status(equipment.status) %>
	</td>
	<td class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
		<b class="caret"></b>
		</a>
		<ul class="dropdown-menu">
			<li><%= link_to "Edit", edit_equipment_path(equipment) %></li>
			<li><%= link_to "Delete", equipment, method: "delete", data: { confirm: "You sure?" } %></li>
		</ul>
	</td>
</tr>

app/views/equipment/_form.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@equipment) do |f| %>	
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :tag %>
			<%= f.text_field :tag, class: 'form-control' %>

			<%= f.label :status %>
			<%= f.select :status, options_for_select([["IN", 2],["OUT", 1]], @equipment.status)%>

			<%= f.submit "Add", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/equipment/edit.html.erb
<% provide(:title, "Edit equipment")%>
<h1>Update <%= @equipment.name %></h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@equipment) do |f| %>	
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :tag %>
			<%= f.text_field :tag, class: 'form-control' %>

			<%= f.label :status %>
			<%= f.select :status, options_for_select([["IN", 2],["OUT", 1]], @equipment.status)%>

			<%= f.submit "Save changes", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/equipment/index.html.erb
<% provide(:title, "All Equipment") %>
<h1>Equipment</h1>
<%= will_paginate %>
<div class="table-responsive">
	<table class="table table-striped">
		<tr>
			<th>
			Tag
			</th>
			<th>
			Name
			</th>
			<th>
			Status
			</th>
			<th>
			Options
			</th>
		</tr>
		<%= render @equipment %>
	</table>
</div>
<%= will_paginate %>

app/views/equipment/new.html.erb
<% provide(:title, 'Add Equipment') %>
<h1>Add Equipment</h1>
<%= render 'equipment/form' %>

app/views/equipment/show.html.erb
<div class="jumbotron">
	<p class="center">
		<b>Equipment Name:</b> "<%= @equipment.name %>", 
		<b>Tag:</b> "<%= @equipment.tag %>", 
		<b>Status:</b> "<%= give_status(@equipment.status)%>"
	</p>
</div>