config/routes.rb
Rails.application.routes.draw do

  root 							          'static_pages#home'
  get   	 'contact' 		  =>  'static_pages#contact'
  get		   'addequipment'	=>	'equipment#new'
  get      'makerequest'  =>  'requests#new'
  get		   'signup' 		  =>	'admins#new'
  get		   'login'			  =>	'sessions#new'
  post		 'login'			  =>	'sessions#create'
  delete	 'logout'		    =>	'sessions#destroy'
  resources :admins do
    member do
      get :signed_out, :signed_out_by
      get :signed_in, :signed_in_by
    end
  end
  resources :equipment
  resources :requests,  only: [:new, :create, :index, :destroy]
  resources :sign_outs,   only: [:create, :destroy]
  resources :sign_ins,   only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<ul>
	 	<li><%= link_to "Contact", contact_path %></li>
	</ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
	<%= link_to "ASU Student Union", '/', id: "logo" %>
	<nav>
		<ul class="nav navbar-nav navbar-right">
		<% if logged_in? %>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				Requests<b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><%= link_to "Index", requests_path %></li>
				</ul>
			</li> 
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				Admins<b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><%= link_to "Add", signup_path %></li>
					<li><%= link_to "Index", admins_path %></li>
				</ul>
			</li> 
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				Equipment<b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><%= link_to "Add", addequipment_path %></li>
					<li><%= link_to "Index", equipment_index_path %></li>
				</ul>
			</li> 
			<li><%= link_to "Log Out", logout_path, method: "delete" %>
		<% else %>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Log in", login_path %></li>
		<% end %>
		</ul>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
     <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
     <% end %>
	   <%= yield %>
     <%= render 'layouts/footer' %>
     <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>